server:
  port: 8080 # 服务端口

spring:
  web:
    resources:
      static-locations: classpath:/static/ # 静态资源位置
  application:
    name: junchuang # 应用名称
  jackson:
    serialization:
      INDENT_OUTPUT: true # 是否格式化 JSON 输出
  redis:
    host: localhost # Redis 主机地址
    port: 6379 # Redis 端口

mqtt:
  url: tcp://${url}:1884 # MQTT 服务器 URL
  username: admin # MQTT 用户名
  password: 123 # MQTT 密码
  send_id: "send_${machineCode}" # 发送 ID
  listen_id: "listen_${machineCode}" # 监听 ID

# 日志配置（仅在 Windows 有效）
logging:
  config: classpath:logbak.xml # 日志配置文件路径

# 机器码
machineCode: A000001 # 用于标识设备的唯一代码

# URL 配置
url: www.zjngic.com # 服务器地址

# 本机 IP 配置
ip:
  local: 192.168.1.2 # 本机 IP 地址
  nettyPort: 5555 # Netty 端口
  plc: 192.168.1.3 # 信号采集设备网关

# 订单价格配置
order:
  prices:
    type1: 10
    type2: 15
    type3: 20
    type4: 30
    type5: 40

